repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.7 # Use a recent stable version
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.0 # Use a recent stable version
    hooks:
      - id: mypy
        args: [ --ignore-missing-imports, --show-error-codes ]
